# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4dcb989355e4c807c463f3c29ad291bb"
name = "Weppo"
handle = "weppo"
application_url = "https://helping-approaches-tribe-fourth.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://helping-approaches-tribe-fourth.trycloudflare.com/auth/callback",
  "https://helping-approaches-tribe-fourth.trycloudflare.com/auth/shopify/callback",
  "https://helping-approaches-tribe-fourth.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
